apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app2025
  labels:
    app: sample-python-app2025
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app2025
  template:
    metadata:
      labels:
        app: sample-python-app2025
    spec:
      containers:
      - name: sample-py-app
        image: adarsh623/python-app
        ports:
        - containerPort: 8000

